trigger: none

pool: Nazruddin

stages:
  - stage: precommitstage
    jobs:
      - job: precommit
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: '1.14.3'

        - task: TerraformTask@5
          inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
              backendServiceArm: 'Nazruddinconnect'
              backendAzureRmStorageAccountName: 'sheikhstg'
              backendAzureRmContainerName: 'sheikhcnt2'
              backendAzureRmKey: 'dev.terraform.tfstate'
        
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
        
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'custom'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
            outputTo: 'console'
            customCommand: 'fmt'
            environmentServiceNameAzureRM: 'Nazruddinconnect'
        
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
            environmentServiceNameAzureRM: 'Nazruddinconnect'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
            environmentServiceNameAzureRM: 'Nazruddinconnect'
